///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MovieTrailerModelResults {
/*
{
  "iso_639_1": "en",
  "iso_3166_1": "US",
  "name": "Theatrical Trailer",
  "key": "hyyyKcfJRGQ",
  "site": "YouTube",
  "size": 2160,
  "type": "Trailer",
  "official": true,
  "published_at": "2023-05-12T02:03:12.000Z",
  "id": "645e47e288b1480158f2e037"
}
*/

  String? iso_639_1;
  String? iso_3166_1;
  String? name;
  String? key;
  String? site;
  int? size;
  String? type;
  bool? official;
  String? publishedAt;
  String? id;

  MovieTrailerModelResults({
    this.iso_639_1,
    this.iso_3166_1,
    this.name,
    this.key,
    this.site,
    this.size,
    this.type,
    this.official,
    this.publishedAt,
    this.id,
  });
  MovieTrailerModelResults.fromJson(Map<String, dynamic> json) {
    iso_639_1 = json['iso_639_1']?.toString();
    iso_3166_1 = json['iso_3166_1']?.toString();
    name = json['name']?.toString();
    key = json['key']?.toString();
    site = json['site']?.toString();
    size = json['size']?.toInt();
    type = json['type']?.toString();
    official = json['official'];
    publishedAt = json['published_at']?.toString();
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['iso_639_1'] = iso_639_1;
    data['iso_3166_1'] = iso_3166_1;
    data['name'] = name;
    data['key'] = key;
    data['site'] = site;
    data['size'] = size;
    data['type'] = type;
    data['official'] = official;
    data['published_at'] = publishedAt;
    data['id'] = id;
    return data;
  }
}

class MovieTrailerModel {
/*
{
  "id": 678512,
  "results": [
    {
      "iso_639_1": "en",
      "iso_3166_1": "US",
      "name": "Theatrical Trailer",
      "key": "hyyyKcfJRGQ",
      "site": "YouTube",
      "size": 2160,
      "type": "Trailer",
      "official": true,
      "published_at": "2023-05-12T02:03:12.000Z",
      "id": "645e47e288b1480158f2e037"
    }
  ]
}
*/

  int? id;
  List<MovieTrailerModelResults?>? results;

  MovieTrailerModel({
    this.id,
    this.results,
  });
  MovieTrailerModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <MovieTrailerModelResults>[];
      v.forEach((v) {
        arr0.add(MovieTrailerModelResults.fromJson(v));
      });
      results = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    return data;
  }
}
