///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MovieDetailModelSpokenLanguages {
/*
{
  "english_name": "Spanish",
  "iso_639_1": "es",
  "name": "Español"
}
*/

  String? englishName;
  String? iso_639_1;
  String? name;

  MovieDetailModelSpokenLanguages({
    this.englishName,
    this.iso_639_1,
    this.name,
  });
  MovieDetailModelSpokenLanguages.fromJson(Map<String, dynamic> json) {
    englishName = json['english_name']?.toString();
    iso_639_1 = json['iso_639_1']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['english_name'] = englishName;
    data['iso_639_1'] = iso_639_1;
    data['name'] = name;
    return data;
  }
}

class MovieDetailModelProductionCountries {
/*
{
  "iso_3166_1": "US",
  "name": "United States of America"
}
*/

  String? iso_3166_1;
  String? name;

  MovieDetailModelProductionCountries({
    this.iso_3166_1,
    this.name,
  });
  MovieDetailModelProductionCountries.fromJson(Map<String, dynamic> json) {
    iso_3166_1 = json['iso_3166_1']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['iso_3166_1'] = iso_3166_1;
    data['name'] = name;
    return data;
  }
}

class MovieDetailModelProductionCompanies {
/*
{
  "id": 90508,
  "logo_path": null,
  "name": "Santa Fe Films",
  "origin_country": "US"
}
*/

  int? id;
  String? logoPath;
  String? name;
  String? originCountry;

  MovieDetailModelProductionCompanies({
    this.id,
    this.logoPath,
    this.name,
    this.originCountry,
  });
  MovieDetailModelProductionCompanies.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    logoPath = json['logo_path']?.toString();
    name = json['name']?.toString();
    originCountry = json['origin_country']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['logo_path'] = logoPath;
    data['name'] = name;
    data['origin_country'] = originCountry;
    return data;
  }
}

class MovieDetailModelGenres {
/*
{
  "id": 28,
  "name": "Action"
}
*/

  int? id;
  String? name;

  MovieDetailModelGenres({
    this.id,
    this.name,
  });
  MovieDetailModelGenres.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class MovieDetailModel {
/*
{
  "adult": false,
  "backdrop_path": "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
  "belongs_to_collection": null,
  "budget": 14500000,
  "genres": [
    {
      "id": 28,
      "name": "Action"
    }
  ],
  "homepage": "https://www.soundoffreedommovie.com/",
  "id": 678512,
  "imdb_id": "tt7599146",
  "original_language": "en",
  "original_title": "Sound of Freedom",
  "overview": "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
  "popularity": 573.294,
  "poster_path": "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
  "production_companies": [
    {
      "id": 90508,
      "logo_path": null,
      "name": "Santa Fe Films",
      "origin_country": "US"
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "US",
      "name": "United States of America"
    }
  ],
  "release_date": "2023-07-03",
  "revenue": 246700000,
  "runtime": 131,
  "spoken_languages": [
    {
      "english_name": "Spanish",
      "iso_639_1": "es",
      "name": "Español"
    }
  ],
  "status": "Released",
  "tagline": "Fight for the light. Silence the darkness.",
  "title": "Sound of Freedom",
  "video": false,
  "vote_average": 8.082,
  "vote_count": 1458
}
*/

  bool? adult;
  String? backdropPath;
  String? belongsToCollection;
  int? budget;
  List<MovieDetailModelGenres?>? genres;
  String? homepage;
  int? id;
  String? imdbId;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  List<MovieDetailModelProductionCompanies?>? productionCompanies;
  List<MovieDetailModelProductionCountries?>? productionCountries;
  String? releaseDate;
  int? revenue;
  int? runtime;
  List<MovieDetailModelSpokenLanguages?>? spokenLanguages;
  String? status;
  String? tagline;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  MovieDetailModel({
    this.adult,
    this.backdropPath,
    this.belongsToCollection,
    this.budget,
    this.genres,
    this.homepage,
    this.id,
    this.imdbId,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.productionCompanies,
    this.productionCountries,
    this.releaseDate,
    this.revenue,
    this.runtime,
    this.spokenLanguages,
    this.status,
    this.tagline,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });
  MovieDetailModel.fromJson(Map<String, dynamic> json) {
    adult = json['adult'];
    backdropPath = json['backdrop_path']?.toString();
    belongsToCollection = json['belongs_to_collection']?.toString();
    budget = json['budget']?.toInt();
    if (json['genres'] != null) {
      final v = json['genres'];
      final arr0 = <MovieDetailModelGenres>[];
      v.forEach((v) {
        arr0.add(MovieDetailModelGenres.fromJson(v));
      });
      genres = arr0;
    }
    homepage = json['homepage']?.toString();
    id = json['id']?.toInt();
    imdbId = json['imdb_id']?.toString();
    originalLanguage = json['original_language']?.toString();
    originalTitle = json['original_title']?.toString();
    overview = json['overview']?.toString();
    popularity = json['popularity']?.toDouble();
    posterPath = json['poster_path']?.toString();
    if (json['production_companies'] != null) {
      final v = json['production_companies'];
      final arr0 = <MovieDetailModelProductionCompanies>[];
      v.forEach((v) {
        arr0.add(MovieDetailModelProductionCompanies.fromJson(v));
      });
      productionCompanies = arr0;
    }
    if (json['production_countries'] != null) {
      final v = json['production_countries'];
      final arr0 = <MovieDetailModelProductionCountries>[];
      v.forEach((v) {
        arr0.add(MovieDetailModelProductionCountries.fromJson(v));
      });
      productionCountries = arr0;
    }
    releaseDate = json['release_date']?.toString();
    revenue = json['revenue']?.toInt();
    runtime = json['runtime']?.toInt();
    if (json['spoken_languages'] != null) {
      final v = json['spoken_languages'];
      final arr0 = <MovieDetailModelSpokenLanguages>[];
      v.forEach((v) {
        arr0.add(MovieDetailModelSpokenLanguages.fromJson(v));
      });
      spokenLanguages = arr0;
    }
    status = json['status']?.toString();
    tagline = json['tagline']?.toString();
    title = json['title']?.toString();
    video = json['video'];
    voteAverage = json['vote_average']?.toDouble();
    voteCount = json['vote_count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['adult'] = adult;
    data['backdrop_path'] = backdropPath;
    data['belongs_to_collection'] = belongsToCollection;
    data['budget'] = budget;
    if (genres != null) {
      final v = genres;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['genres'] = arr0;
    }
    data['homepage'] = homepage;
    data['id'] = id;
    data['imdb_id'] = imdbId;
    data['original_language'] = originalLanguage;
    data['original_title'] = originalTitle;
    data['overview'] = overview;
    data['popularity'] = popularity;
    data['poster_path'] = posterPath;
    if (productionCompanies != null) {
      final v = productionCompanies;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['production_companies'] = arr0;
    }
    if (productionCountries != null) {
      final v = productionCountries;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['production_countries'] = arr0;
    }
    data['release_date'] = releaseDate;
    data['revenue'] = revenue;
    data['runtime'] = runtime;
    if (spokenLanguages != null) {
      final v = spokenLanguages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['spoken_languages'] = arr0;
    }
    data['status'] = status;
    data['tagline'] = tagline;
    data['title'] = title;
    data['video'] = video;
    data['vote_average'] = voteAverage;
    data['vote_count'] = voteCount;
    return data;
  }
}
