///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpcomingMovieModelResults {
/*
{
  "adult": false,
  "backdrop_path": "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
  "genre_ids": [
    28
  ],
  "id": 678512,
  "original_language": "en",
  "original_title": "Sound of Freedom",
  "overview": "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
  "popularity": 573.294,
  "poster_path": "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
  "release_date": "2023-07-03",
  "title": "Sound of Freedom",
  "video": false,
  "vote_average": 8.085,
  "vote_count": 1449
}
*/

  bool? adult;
  String? backdropPath;
  List<int?>? genreIds;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  bool? video;
  double? voteAverage;
  int? voteCount;

  UpcomingMovieModelResults({
    this.adult,
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.video,
    this.voteAverage,
    this.voteCount,
  });
  UpcomingMovieModelResults.fromJson(Map<String, dynamic> json) {
    adult = json['adult'];
    backdropPath = json['backdrop_path']?.toString();
    if (json['genre_ids'] != null) {
      final v = json['genre_ids'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      genreIds = arr0;
    }
    id = json['id']?.toInt();
    originalLanguage = json['original_language']?.toString();
    originalTitle = json['original_title']?.toString();
    overview = json['overview']?.toString();
    popularity = json['popularity']?.toDouble();
    posterPath = json['poster_path']?.toString();
    releaseDate = json['release_date']?.toString();
    title = json['title']?.toString();
    video = json['video'];
    voteAverage = json['vote_average']?.toDouble();
    voteCount = json['vote_count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['adult'] = adult;
    data['backdrop_path'] = backdropPath;
    if (genreIds != null) {
      final v = genreIds;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['genre_ids'] = arr0;
    }
    data['id'] = id;
    data['original_language'] = originalLanguage;
    data['original_title'] = originalTitle;
    data['overview'] = overview;
    data['popularity'] = popularity;
    data['poster_path'] = posterPath;
    data['release_date'] = releaseDate;
    data['title'] = title;
    data['video'] = video;
    data['vote_average'] = voteAverage;
    data['vote_count'] = voteCount;
    return data;
  }
}

class UpcomingMovieModelDates {
/*
{
  "maximum": "2023-12-13",
  "minimum": "2023-11-22"
}
*/

  String? maximum;
  String? minimum;

  UpcomingMovieModelDates({
    this.maximum,
    this.minimum,
  });
  UpcomingMovieModelDates.fromJson(Map<String, dynamic> json) {
    maximum = json['maximum']?.toString();
    minimum = json['minimum']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['maximum'] = maximum;
    data['minimum'] = minimum;
    return data;
  }
}

class UpcomingMovieModel {
/*
{
  "dates": {
    "maximum": "2023-12-13",
    "minimum": "2023-11-22"
  },
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      "genre_ids": [
        28
      ],
      "id": 678512,
      "original_language": "en",
      "original_title": "Sound of Freedom",
      "overview": "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
      "popularity": 573.294,
      "poster_path": "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
      "release_date": "2023-07-03",
      "title": "Sound of Freedom",
      "video": false,
      "vote_average": 8.085,
      "vote_count": 1449
    }
  ],
  "total_pages": 31,
  "total_results": 604
}
*/

  UpcomingMovieModelDates? dates;
  int? page;
  List<UpcomingMovieModelResults?>? results;
  int? totalPages;
  int? totalResults;

  UpcomingMovieModel({
    this.dates,
    this.page,
    this.results,
    this.totalPages,
    this.totalResults,
  });
  UpcomingMovieModel.fromJson(Map<String, dynamic> json) {
    dates = (json['dates'] != null) ? UpcomingMovieModelDates.fromJson(json['dates']) : null;
    page = json['page']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <UpcomingMovieModelResults>[];
      v.forEach((v) {
        arr0.add(UpcomingMovieModelResults.fromJson(v));
      });
      results = arr0;
    }
    totalPages = json['total_pages']?.toInt();
    totalResults = json['total_results']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dates != null) {
      data['dates'] = dates!.toJson();
    }
    data['page'] = page;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    data['total_pages'] = totalPages;
    data['total_results'] = totalResults;
    return data;
  }
}
